617136488840429598: # TMW
    1314993571647979570: 1301694741083328565  # TMW Owner -> Sharing
    1026918224266280960: 1301694741083328565  # Eternal Idol -> Sharing
    1026918330566721576: 1301694741083328565  # Divine Idol -> Sharing
    795699221365260359: 1301694741083328565   # Prima Idol -> Sharing
    795699163144126474: 1301694741083328565   # Major Idol -> Sharing
    795699064409948210: 1301694741083328565   # Debut Idol -> Sharing
    795698963494731806: 1301694741083328565   # Trainee -> Sharing
    795698879227887678: 1301694741083328565   # Student -> Sharing
    779369584997957723: 1301694741083328565   # Supporter -> Sharing
    779369584997957723: 1302271426270859325   # Supporter -> Custom Role
    1300745834232680448: 1302271426270859325  # Moderator -> Custom Role
    1314993571647979570: 1302271426270859325  # TMW Owner -> Custom Role
    1310487640608342056: 1302271426270859325  # Immortal Idol -> Custom Role

1297383002610995272: # Test Guild
    1297383002849935455: 1297383002849935456  # Mod -> Admin
